/* src/Teko_config.h.in.  Generated by me! */

#define HAVE_Teko_ENABLE_Ifpack2

/* For enabling probing */
#define Teko_ENABLE_Isorropia

/* For development mode */
#define Teko_ENABLE_DEV_MODE
/* #undef Teko_ENABLE_ML_SMOOTHERS */
#define Teko_DEBUG_OFF
