# LOBPCGEpetraExSimple.cpp must be in the current working cirectory

# include /include/Makefile.export.Trilinos

LOBPCGEpetraExSimple.exe LOBPCGEpetraExSimple.cpp
$ (Trilinos CXX COMPILER) $ (Trilinos CXX COMPILER FLAGS) \
LOBPCGEpetraExSimple.cpp −o LOBPCGEpetraExSimple.exe \
$ (Trilinos INCLUDE DIRS) $ (Trilinos TPL INCLUDE DIRS) \
$ (Trilinos LIBRARY DIRS) $ (Trilinos_LIBRARIES) \
$ (Trilinos_TPL_LIBRARIES) $ (Trilinos_EXTRA_LD_FLAGS)

# When running "make clean"
clean:
rm −f LOBPCGEpetraExSimple . e x e LOBPCGEpetraExSimple . o
