IRRLICHT_PATH = /opt/hamzstlib/Physics/irrlicht-1.8.5/

SYSTEM=Linux

CPPFLAGS += -I$(IRRLICHT_PATH)/include
ifndef NDEBUG
CXXFLAGS += -g -Wall
else
CXXFLAGS += -O3
endif

# mirrored from the irrlicht example code (included in the irrlicht path: $(IRRLICHT_PATH)/examples
